title: Baddie Grafisch Vormgever Amsterdam
url: baddie.nl
logo_text: 'Baddie'
logo_image: false
colorset: blue
header_image: /uploads/lama2.jpg
has_home: true
has_about: false
has_pricing: false
has_services: false
has_products: false
has_portfolio: false
has_blog: false
has_contact: true
home_name: Home
about_name: Over ons
pricing_name: Prijzen
services_name: Diensten
products_name: Templates
portfolio_name: Portfolio
blog_name: Blog
contact_name: Contact